export const products = [
    {
      id: 1,
      title: "Sesame Sauce",
      description: "black in color",
      price: "Rs.1,065",
      img: "/images/sesamesauce.png",
      quantity: 1,
    },
    {
      id: 2,
      title: "Soy Sauce",
      description: "white in color",
      price: "Rs.1,065",
      img: "/images/soysauce.png",
      quantity: 1,
    },
    {
      id: 3,
      title: "Veg Chicken",
      description: "black in color",
      price: "Rs.170",
      img: "/images/vegchicken.png",
      quantity: 1,
    },
    {
      id: 4,
      title: "Veg Lollipop",
      description: "Best mobile ever",
      price: "Rs.330",
      img: "/images/veglollipop.png",
      quantity: 1,
    },
    {
      id: 5,
      title: "Veg Sausage",
      description: "black in color",
      price: "Rs.299",
      img: "/images/vegsausage.png",
      quantity: 1,
    },
    {
      id: 6,
      title: "Veg Meat",
      description: "black in color",
      price: "170",
      img: "/images/vegmeat.png",
      quantity: 1,
    },
  ];